// Generated by tools/build-media-cache.cjs; cache media only, never HTML or scripts.
const MEDIA_REVISIONS = {
  "assets/audio/BGM.mp3": "c81d5e33055b91659d27f33d",
  "assets/audio/MAP.mp3": "0eea8130856b234978f20907",
  "assets/audio/sfx/barrier-lv5.mp3": "b44c3028bc599695e015480a",
  "assets/audio/sfx/boomerang.mp3": "03179b832f47c570d5395021",
  "assets/audio/sfx/boss-death.mp3": "bcdc55ae43c253592ad946a1",
  "assets/audio/sfx/break-shield.mp3": "6c0510ce660bafb0e8580917",
  "assets/audio/sfx/dash.mp3": "23d8c1cf6df82ba9ba73a7d7",
  "assets/audio/sfx/delivery-success.mp3": "7737988372bff1bda19ae91c",
  "assets/audio/sfx/delivery-wrong.mp3": "f6e2bec5eaf4e522d87c4e1c",
  "assets/audio/sfx/fanfare.mp3": "c1c74429cf20003026304ac3",
  "assets/audio/sfx/fire-lv1-4.mp3": "bb09dbfb48b98b984c351e99",
  "assets/audio/sfx/fire-lv5.mp3": "605bd12c9c84b3a8aece0b57",
  "assets/audio/sfx/level-up.mp3": "e5f5bca990ea21836bcf2c67",
  "assets/audio/sfx/lose.mp3": "474fd0c4e5f3bb2e56ae92be",
  "assets/audio/sfx/needle.mp3": "e3d10d2208ca466fd7b23ef0",
  "assets/audio/sfx/sanctuary.mp3": "ad998e6db42e0c6f6eda7c2e",
  "assets/audio/sfx/slash.mp3": "ecfca73464a7627427268f55",
  "assets/audio/sfx/warning-pulse.mp3": "eb9050897ae89bd5d098de9a",
  "assets/audio/words/ame.mp3": "bea707ffc1ceb511538c73b0",
  "assets/audio/words/eki.mp3": "e984c5374082254e5719f14b",
  "assets/audio/words/fune.mp3": "0c9e757fb67cdc070d428296",
  "assets/audio/words/hana.mp3": "9663af3b03de512e415674c4",
  "assets/audio/words/hidari.mp3": "de77f3f66d7ee9eb8d1a1e36",
  "assets/audio/words/hikouki.mp3": "b2b4f38e7889ba91b3d3d00c",
  "assets/audio/words/hon.mp3": "3d0788ee715ee280a4836e78",
  "assets/audio/words/hoshi.mp3": "7614216c7ca769c4e4bfff8e",
  "assets/audio/words/inu.mp3": "fe65716cb2f783c7b917227b",
  "assets/audio/words/kaeru.mp3": "538156232b8a173a16e86829",
  "assets/audio/words/kame.mp3": "2b5e62b9d3006309d026de1f",
  "assets/audio/words/kaminari.mp3": "10728f3bf80185a9847de2fc",
  "assets/audio/words/kasa.mp3": "f260ae66b91cb837951f82da",
  "assets/audio/words/kaze.mp3": "cadb6f49008ec35e4e01e701",
  "assets/audio/words/keeki.mp3": "8c799cfb8d5ffc9386b77f7c",
  "assets/audio/words/kiri.mp3": "1a54bcc1d70f193bf8eb25ee",
  "assets/audio/words/kita.mp3": "99efe79b40d658fc55376860",
  "assets/audio/words/kumo.mp3": "c82ba6729c07e993468b69d7",
  "assets/audio/words/kuruma.mp3": "10c37a6756e523a7f0fa319c",
  "assets/audio/words/mae.mp3": "fd81f184ec9785f2c3875cda",
  "assets/audio/words/migi.mp3": "3c412df175111fc993e76af6",
  "assets/audio/words/minami.mp3": "cc1bc8ed7044f056f5e66151",
  "assets/audio/words/neko.mp3": "ed0a2bb561593cd42012d5ae",
  "assets/audio/words/niji.mp3": "de8c5f1ef1193a8377fac1f0",
  "assets/audio/words/ocha.mp3": "8539696c17b885e763039279",
  "assets/audio/words/onigiri.mp3": "3ca52803435e8b43759b72b1",
  "assets/audio/words/pan.mp3": "17d27b8c181a60b2b77aa3ee",
  "assets/audio/words/ramen.mp3": "fc7e885119687da59d01bbef",
  "assets/audio/words/ringo.mp3": "e841a71225cc377ee74143ad",
  "assets/audio/words/sakana.mp3": "3e3b057e9477cfaba6793843",
  "assets/audio/words/sakura.mp3": "1d7171d228f7887f9befd022",
  "assets/audio/words/tako.mp3": "f31ed73a70486c68ad2b1d2c",
  "assets/audio/words/tori.mp3": "fcd23676f78d7e1e07f6189b",
  "assets/audio/words/tsuki.mp3": "c724209a765ec9589c964303",
  "assets/audio/words/umi.mp3": "da09f87cf69baec5cabb1750",
  "assets/audio/words/usagi.mp3": "bc010163ecffc1759d91a651",
  "assets/audio/words/ushiro.mp3": "00c8b2617cef7dc106274428",
  "assets/audio/words/yama.mp3": "5af697c41fe08db43cdb8775",
  "assets/audio/words/yuki.mp3": "838b8b2f327a76e06a45fe62",
  "assets/img/boss.png": "2d7a89ac4a73a6d44777d41b",
  "assets/img/boss.webp": "cb97fcb25a1c9361554f743b",
  "assets/img/boss_motion_v1.png": "1835909dfb0b7d408386ce45",
  "assets/img/boss_motion_v1.webp": "4fc3763d236ee06281f5ae8e",
  "assets/img/cover.jpg": "31b06735f2b943c8ca6b753e",
  "assets/img/cover.webp": "af807c3e29426fe5494e7fbc",
  "assets/img/ghost.png": "3a70cb8ee729d36eda8da32b",
  "assets/img/ghost.webp": "23e2929d592079d61580b34b",
  "assets/img/ghost_motion_v1.png": "2776ac942e2b784aecd76eb0",
  "assets/img/ghost_motion_v1.webp": "99d7ebe1484e4e807a25f6d9",
  "assets/img/ground.png": "cc44be8c0516da4b934278bf",
  "assets/img/ground.webp": "3bc3098353957dbe7847b329",
  "assets/img/ground_dirt.png": "48a440240d3d056388f3f0a6",
  "assets/img/ground_dirt.webp": "efb1502aeb4fe8e4ca935c3c",
  "assets/img/house_shop.png": "97cb9e88437d6bd4e49c1df7",
  "assets/img/house_shop.webp": "f578f276ba4e0e0298001b1a",
  "assets/img/house_shrine.png": "3cd31360ca3654e36dcb062c",
  "assets/img/house_shrine.webp": "90e40f633e2deefd5a34d6dc",
  "assets/img/house_tavern.png": "4b14eac031a3f4715623bbef",
  "assets/img/house_tavern.webp": "e6c25e3f7891f73b9d1d5ddf",
  "assets/img/map_night_town_v1.png": "68238618784cd5f32c1750cf",
  "assets/img/map_night_town_v1.webp": "423f6e3e4af12d0ea88c809e",
  "assets/img/map_rain_port_v1.png": "11e188bb6305503e4fd9043c",
  "assets/img/map_rain_port_v1.webp": "3cde1356b277643f3e60b471",
  "assets/img/mis.png": "10fe3f9e3857ceffd383ec86",
  "assets/img/mis.webp": "c394297a978b3beb14fbe267",
  "assets/img/mis_motion_v1.png": "f5d7c7cbf60bb3a289c13e35",
  "assets/img/mis_motion_v1.webp": "43e0c637d27f7fa228ca375b",
  "assets/img/overworld_night_v1.png": "bd51dfa004360d66563254e1",
  "assets/img/overworld_night_v1.webp": "9c43c64073cde2a39e1ae5a1",
  "assets/img/overworld_night_v2.png": "f29d6c7547970846a0f82e31",
  "assets/img/overworld_night_v2.webp": "fa7d326067e4ac838093a159",
  "assets/img/player.png": "0b0cb44d08245a7743ca8470",
  "assets/img/player.webp": "3a1385a0baf403b70f7cf9cd",
  "assets/img/player_dash_v1.png": "29cea003e9ebb4ef45705e9c",
  "assets/img/player_dash_v1.webp": "5f76d599bb225aae89adad65",
  "assets/img/player_kneel_v1.png": "64895afc389f1eabe489fae9",
  "assets/img/player_kneel_v1.webp": "4a0ba200641076a0237305a1",
  "assets/img/player_rest_v1.webp": "2dcec0c2c5c8f8f4f35eea46",
  "assets/img/player_walk1.png": "b4872ef678abef338507b7e4",
  "assets/img/player_walk1.webp": "37ee07bd7dfc0ac51cd940cb",
  "assets/img/player_walk2.png": "e9d63322d87e45be8c1cc740",
  "assets/img/player_walk2.webp": "f7ba693f109aa4e7c4e97952",
  "assets/img/player_walk_spritesheet_raw.jpg": "cf9a2968e339b77d0bc5b0f4",
  "assets/img/player_win_v1.png": "64327415cdbcc0efcee3a103",
  "assets/img/player_win_v1.webp": "61b3e33373004750fcbe1a2d",
  "assets/img/prop_lantern.png": "cc8e150c388dae7e3f6423f2",
  "assets/img/prop_lantern.webp": "456509dd4184908f0aa9da31",
  "assets/img/prop_sakura.png": "8a899065caa70ddabb99cefb",
  "assets/img/prop_sakura.webp": "54b8b4fcac9d7a45119ef1cd",
  "assets/img/prop_torii.png": "e687601985c07824b19817b5",
  "assets/img/prop_torii.webp": "c4efb162f96f95a78cb3eb74",
  "assets/img/runner.png": "0ae5a5964645a3d9940811e3",
  "assets/img/runner.webp": "020fcd9323f75a59f7f064fe",
  "assets/img/runner_motion_v1.png": "3e97f8291320610199812166",
  "assets/img/runner_motion_v1.webp": "ef83e70b99321550fbb24c57",
  "assets/img/scenery/ground.webp": "4bf18cb0c29a256947d3008e",
  "assets/img/scenery/ground_dirt.webp": "d8a5a5d885cff6c64f7912a5",
  "assets/img/scenery/house_shop.webp": "459ce1e5db4a016eb72739c8",
  "assets/img/scenery/house_shrine.webp": "a304f888c5984b01017670c9",
  "assets/img/scenery/house_tavern.webp": "dd9aaddd9dfdd0a91ccdad16",
  "assets/img/scenery/prop_lantern.webp": "80810970ef33c0ab9767bd53",
  "assets/img/scenery/prop_sakura.webp": "14b68a049d8654a182f751ef",
  "assets/img/scenery/prop_torii.webp": "ee1f74e20d87445c1fe180d7",
  "assets/img/shooter.png": "8b03766736d4020a81eab32d",
  "assets/img/shooter.webp": "ebed7c0b3ae502f0e50c73d8",
  "assets/img/shooter_motion_v1.png": "377ec5e16657cee5cfbedb54",
  "assets/img/shooter_motion_v1.webp": "1fb630e40036235b84eb2193",
  "assets/img/tank.png": "4fb22ef9a959c64851a0b724",
  "assets/img/tank.webp": "fad88f4ddeae620e16d3220d",
  "assets/img/tank_motion_v1.png": "d7aadc6932d1d2f4bf64bacd",
  "assets/img/tank_motion_v1.webp": "c5491157893ccf8286f1abc7",
  "assets/img/ui/hud_lantern_oil.png": "0dc0efee8701805d0dbf9d2d",
  "assets/img/ui/hud_lantern_oil.webp": "8a2f5e50a17cfdb3919d5732",
  "assets/img/ui/hud_omamori_hint_listen.png": "4ed543edb845c8d4993ff9c6",
  "assets/img/ui/hud_omamori_hint_listen.webp": "f9c9d63a3f0c5a85dab1f5e2",
  "assets/img/ui/hud_radar_frame.png": "e86480b301fed05c22dc839f",
  "assets/img/ui/hud_radar_frame.webp": "f8f827eab7896ae1961a038d",
  "assets/img/ui/hud_skill_fan.png": "60fb80accb13412dca11ef33",
  "assets/img/ui/hud_skill_fan.webp": "fc498d6f49e8c14a452d6806",
  "assets/img/ui/illustrated/button_danger.webp": "f718a91dbcbbc11b05d3d7ae",
  "assets/img/ui/illustrated/button_primary.webp": "d793eb710115d0d0ef742ea7",
  "assets/img/ui/illustrated/button_secondary.webp": "0e5c4d8a8f651f7b5235c44f",
  "assets/img/ui/illustrated/pause_panel.webp": "da0da663e132ae89ec4cde3a",
  "assets/img/ui/illustrated/result_panel.webp": "48d7e7c46010a6f38d38b086",
  "assets/img/ui/illustrated/title_tag.webp": "cc5b01601f3d9ec7a36b6730",
  "assets/img/ui/ledger_washi.webp": "71a72f3f1f15a320a719d848",
  "assets/img/ui/notice_washi.webp": "37290bd8e651a909419730da",
  "assets/img/ui/ofuda_cyan.webp": "0ff0232563ddfa34240337d5",
  "assets/img/ui/ofuda_neutral.webp": "247f3b61d38805f252ec8d5c",
  "assets/img/ui/ofuda_vermilion.webp": "73ae56a6c960cab6cf5bf06d",
  "assets/img/vfx/barrier_mandala_ukiyoe.svg": "3bf67dd1854be1206038fd25",
  "assets/img/vfx/foxfire_dragon_ukiyoe.svg": "e44254494c164bf0c7d08f76",
  "assets/img/vfx/foxfire_ukiyoe.svg": "47753cee2dea33a3ca9dd030",
  "assets/img/vfx/katana_wave_ukiyoe.svg": "41bf41608dde307ec695174f",
  "assets/img/vfx/needle_hama_ukiyoe.svg": "7e75f53e443ca7933ea93c83",
  "assets/img/vfx/needle_ice_ukiyoe.svg": "c68fa0d8c6efd09513eb7f28",
  "assets/img/vfx/ofuda_ukiyoe.svg": "9790b1818df4dc6b5b5683ed",
  "assets/img/vfx/raster/barrier_ground_45.webp": "fdde6501d0e147a6b08aacaa",
  "assets/img/vfx/raster/dragon_burning_ground_l5.webp": "30b6e87d4c99fcf2c0cd5d6b",
  "assets/img/vfx/raster/dragon_fireball_l5.webp": "f24c5e271300bd8b0985eebc",
  "assets/img/vfx/raster/fire_attack_l1.webp": "9783eae4a973375612ba7219",
  "assets/img/vfx/raster/fire_attack_l2.webp": "0415e95744896c146f360297",
  "assets/img/vfx/raster/fire_attack_l3.webp": "4ac3a54ca8cb487b3535fd25",
  "assets/img/vfx/raster/fire_attack_l4.webp": "4c9f17a2cca840faafa7e323",
  "assets/img/vfx/raster/fire_attack_l5.webp": "1ff6f01ea10515ced7fa2fc1",
  "assets/img/vfx/raster/fire_dragon_l5.webp": "6eea4b5fad59d305c0d34f95",
  "assets/img/vfx/raster/fire_orbit_l1.webp": "d805c9ede255f5f0575ad655",
  "assets/img/vfx/raster/fire_orbit_l2.webp": "b852233f32429648488b6073",
  "assets/img/vfx/raster/fire_orbit_l3.webp": "32db0a5b1020bb0ad014ad79",
  "assets/img/vfx/raster/fire_orbit_l4.webp": "65c8f606172335e278a2f22a",
  "assets/img/vfx/raster/fire_orbit_l5.webp": "a31eb875e4ccca1e009191c6",
  "assets/img/vfx/raster/foxfire.webp": "1f3bf05ccd00de8143e32acf",
  "assets/img/vfx/raster/foxfire_dragon.webp": "d81e331f2d83363fa7cc86b1",
  "assets/img/vfx/raster/katana.webp": "6d69d4753e83e70af08d1724",
  "assets/img/vfx/raster/katana_l1.webp": "2adb6d972b804cda6f5fa67d",
  "assets/img/vfx/raster/katana_l2.webp": "a3c52be3ea7c7c2e421cb863",
  "assets/img/vfx/raster/katana_l3.webp": "e82548cd4cfc7c4a8df50165",
  "assets/img/vfx/raster/katana_l4.webp": "4dafc2ffbc65dc621507ebc6",
  "assets/img/vfx/raster/katana_l5.webp": "7c4373899db1ea53eea9eec1",
  "assets/img/vfx/raster/needle.webp": "a1c7fe09d51df02e892d8680",
  "assets/img/vfx/raster/ofuda.webp": "d03a42999f3006ba0d37f317",
  "assets/img/vfx/raster/thunder_cloud_45.webp": "2637d2b2b5a863206b3b094b",
  "assets/img/vfx/raster/thunder_strike.webp": "e5559f401a6bf88e8df68e66",
  "assets/img/vfx/taiji_ofuda_ukiyoe.svg": "e4a27fe700c5b14109b6dd01",
  "assets/img/vfx/thunder_drum_ukiyoe.svg": "8a16c8682bded8b562337be3",
  "assets/img/vfx/thunder_ukiyoe.svg": "5987976481b1e56df18c3bea",
  "assets/img/yokai/boss.webp": "84fc3b5ddf955fb6f088fa27",
  "assets/img/yokai/boss_motion_v1.webp": "3c1b6df7dfa25e714e33410f",
  "assets/img/yokai/ghost.webp": "49d30a9aa837b6d3335221ea",
  "assets/img/yokai/ghost_motion_v1.webp": "5fde819a21b89a073dc845ef",
  "assets/img/yokai/mis.webp": "0941497239d28e03955d60ad",
  "assets/img/yokai/mis_motion_v1.webp": "1626818c4719020895c78ee9",
  "assets/img/yokai/runner.webp": "8e47a64c084f1888efb68f8e",
  "assets/img/yokai/runner_motion_v1.webp": "ea46f2ede417a6c8de6802ba",
  "assets/img/yokai/shooter.webp": "21015debd37b7e11a42b47c3",
  "assets/img/yokai/shooter_motion_v1.webp": "5d69f8be15c9192459b6d2ba",
  "assets/img/yokai/tank.webp": "f5ffe33776f3131d61bb4f2a",
  "assets/img/yokai/tank_motion_v1.webp": "24aeaba98e685e4619487a2c"
};
const CACHE_NAME = 'yokai-media-v1';
const scope = self.registration.scope;
const cacheKey = (path, revision) => new URL(path + '?revision=' + revision, scope).href;
self.addEventListener('install', event => event.waitUntil(self.skipWaiting()));
self.addEventListener('activate', event => event.waitUntil((async () => {
  const cache = await caches.open(CACHE_NAME);
  const current = new Set(Object.entries(MEDIA_REVISIONS).map(([path, revision]) => cacheKey(path, revision)));
  for (const request of await cache.keys()) if (!current.has(request.url)) await cache.delete(request);
  await self.clients.claim();
})()));

async function serveMedia(event, path, revision) {
  const key = cacheKey(path, revision);
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(key);
  if (!cached) {
    // Safari probes audio with tiny ranges; preserve them instead of downloading the entire song.
    if (event.request.headers.has('Range')) return fetch(event.request);
    const response = await fetch(key, { cache: 'no-store' });
    if (response.status === 200) event.waitUntil(cache.put(key, response.clone()).catch(() => {}));
    return response;
  }
  const range = event.request.headers.get('Range');
  if (!range) return cached;
  const match = /^bytes=(\d*)-(\d*)$/.exec(range);
  if (!match || (!match[1] && !match[2])) return fetch(event.request);
  const bytes = await cached.arrayBuffer(), size = bytes.byteLength;
  const start = match[1] ? Number(match[1]) : Math.max(0, size - Number(match[2]));
  const end = match[1] ? (match[2] ? Math.min(Number(match[2]), size - 1) : size - 1) : size - 1;
  if (start >= size || start > end) return new Response(null, { status: 416, headers: { 'Content-Range': `bytes */${size}` } });
  const headers = new Headers(cached.headers);
  headers.set('Content-Range', `bytes ${start}-${end}/${size}`);
  headers.set('Content-Length', String(end - start + 1));
  headers.set('Accept-Ranges', 'bytes');
  return new Response(bytes.slice(start, end + 1), { status: 206, headers });
}

self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET') return;
  const url = new URL(event.request.url), base = new URL(scope);
  if (url.origin !== base.origin || !url.pathname.startsWith(base.pathname)) return;
  const path = url.pathname.slice(base.pathname.length), revision = MEDIA_REVISIONS[path];
  if (revision) event.respondWith(serveMedia(event, path, revision).catch(() => fetch(event.request)));
});
