const fs=require('node:fs');const {chromium}=require('C:/Users/York/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
let browser;(async()=>{browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const page=await browser.newPage({viewport:{width:1280,height:720}}),errors=[],evidence=[];page.on('pageerror',e=>errors.push(e.message));
 for(const skill of ['katana','thunder','barrier','boom','fire']){
  await page.goto('http://127.0.0.1:8796/artifacts/validation/skillfx-lab-cell.html?skill='+skill+'&level=5');await page.waitForFunction(()=>ART_READY);
  await page.evaluate(()=>postMessage({type:'skillLab',cmd:'keyframe'},location.origin));await page.waitForTimeout(300);await page.screenshot({path:'artifacts/validation/round25-'+skill+'.png'});
  const frozen=await page.evaluate(()=>labEvidence());await page.evaluate(()=>postMessage({type:'skillLab',cmd:'reset'},location.origin));await page.waitForTimeout(350);const moving=await page.evaluate(()=>labEvidence());
  if(moving.paused||moving.elapsed<=0||(await page.locator('#lab-status').textContent()).startsWith('ERROR:'))throw new Error('Replay did not resume '+skill+' '+JSON.stringify({moving,status:await page.locator('#lab-status').textContent(),errors}));evidence.push({skill,frozen,moving});
 }
 await page.goto('http://127.0.0.1:8796/artifacts/validation/max-three-preview.html');await page.waitForTimeout(400);const cell=page.frames().find(f=>f.url().includes('skillfx-lab-cell'));await cell.waitForFunction(()=>ART_READY);await page.getByRole('button',{name:'六招同場'}).click();await page.waitForTimeout(1500);await page.getByRole('button',{name:'暫停',exact:true}).click();await page.screenshot({path:'artifacts/validation/round25-mixed.png'});await page.getByRole('button',{name:'重播',exact:true}).click();await page.waitForTimeout(300);if((await cell.evaluate(()=>labEvidence())).paused)throw new Error('Parent replay stuck');
 await page.setViewportSize({width:844,height:390});await page.goto('http://127.0.0.1:8796/artifacts/validation/skillfx-lab-cell.html?skill=barrier&level=5&motion=reduce');await page.waitForFunction(()=>ART_READY);await page.waitForTimeout(200);await page.screenshot({path:'artifacts/validation/round25-mobile-reduced.png'});
 const report={errors,evidence,controlled:true,productionSkillCode:true};fs.writeFileSync('artifacts/validation/round25-browser.json',JSON.stringify(report,null,2));console.log(JSON.stringify({errors,skills:evidence.length,replayResumes:true}));await browser.close();if(errors.length)process.exitCode=1;})().catch(async e=>{console.error(e);await browser?.close();process.exitCode=1});
